# Ref: https://docs.ansible.com/ansible/latest/user_guide/playbooks_vars_facts.html


---
#  display the system details
- name: display the system details
  debug:
    msg:
      - "Inventory hostname is {{ inventory_hostname }}"
      - "Hostname is {{ ansible_hostname }}"
      - "OS family is {{ ansible_os_family }}"
      - "OS distribution is {{ ansible_distribution }}"
      - "OS distribution version is {{ ansible_distribution_major_version }}"
      - "Package manager is {{ ansible_pkg_mgr }}"
      - "Service manager is {{ ansible_service_mgr }}"
      - "Architecture is {{ ansible_architecture }}"
      - "RAM is {{ ansible_memtotal_mb }}"
      - "Processor is {{ ansible_processor[2] }}"
      - "Processor count is {{ ansible_processor_count }}"
      - "Processor cores is {{ ansible_processor_cores }}"
      - "Processor threads per core is {{ ansible_processor_threads_per_core }}"
      - "Processor vcpus is {{ ansible_processor_vcpus }}"
      - "Product name is {{ ansible_product_name }}"
      - "Product serial is {{ ansible_product_serial }}"
      - "Product UUID is {{ ansible_product_uuid }}"
      - "Product version is {{ ansible_product_version }}"
      - "Python executable is {{ ansible_python.executable }}"
      - "Python version is {{ ansible_python_version }}"
