# Ref: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/pip_module.html
#         https://github.com/ansible/ansible/issues/42699
#         https://docs.ansible.com/ansible/2.4/playbooks_loops.html#loop-control
#         https://stackoverflow.com/questions/23264226/how-to-write-dynamic-variable-in-ansible-playbook


---

- name: pre-run | include vars related packages
  include_vars:
    dir: /home/wiu/ms/ansible/ansible/group_vars/packages
    extensions:
      - ''
      - 'yaml'
      - 'yml'
      - 'json'


- name: system setup | python packages | install pip packages
  tags: bpytop,packages,pip,python
  # become_user: "{{ main_user }}"
  # pip:
  #   state: "{{ item[0] }}"
  #   name: "{{ item[1] }}"
  #   executable: "{{ item[2] }}"
  debug:
    msg:
    - "state: {{ item[0] }}"
    - "name: {{ item[1] }}"
    - "executable: {{ item[2] }}"
  with_items:
     - "{{ package_list['pip'] }}"