# Ref: https://docs.ansible.com/ansible/2.6/modules/docker_module.html
#         https://docs.ansible.com/ansible/latest/collections/community/general/docker_image_module.html
#         https://docs.ansible.com/ansible/latest/collections/community/general/docker_container_module.html
#         https://docs.ansible.com/ansible/latest/collections/community/general/docker_compose_module.html
#         https://www.redhat.com/sysadmin/container-images-ansible


---
# tasks file for manage_docker

# docker | ensure docker python module requirements are fulfilled
- name: Ensure docker python module is present
  include_vars:
    file: ../group_vars/docker

# docker | ensure docker python module requirements are fulfilled
- name: Ensure docker python module is present
  pip:
    requirements: "{{playbook_dir}}/../requirements.txt"
    state: present      #absent/present


# "{{ action }}"t a docker container
- name: docker | "{{ action }}" "{{ item }}"  container
  docker_container:
    name: "{{ item }}"
    image: "{{ item }}"
    state: "{{ action }}"
  with_items:
    - "{{ image_name }}"


# # docker | run task based on value passed in a variable named "action"
# - include_tasks: '{{ action }}.yml'