# Ref: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/package_module.html
#         https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
#         https://docs.ansible.com/ansible/latest/collections/community/general/pacman_module.html


---
#  ***** ***** Distro: Debian and Module: apt ***** *****

# import os name list
- name: pre-run | vars related to OS category
  include_vars:
    dir: /home/wiu/ms/ansible/ansible/group_vars/os
    extensions:
      - ''
      - 'yaml'
      - 'yml'
      - 'json'

# run the equivalent of "apt-get update"
#   only run "update_cache=yes" if the last one is more than 3600 seconds ago
- name: pre-run | update package cache (debian based distros)
  tags: always
  apt:
    update_cache: yes
    cache_valid_time: 3600
  changed_when: False
  when: ansible_distribution in apt_based_distro


#  ***** ***** Distro: RedHat and Module: yum ***** *****

- name: pre-run | update package cache (RedHat based distros)
  tags: always
  yum:
    update_cache: yes
  changed_when: False
  when: ansible_distribution in yum_based_distro


#  ***** ***** Distro: Archlinux and Module: pacman ***** *****

- name: pre-run | update package cache (arch)
  tags: always
  pacman:
    update_cache: yes
  changed_when: False
  when: ansible_distribution in pacman_based_distro
